<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StarThrower.ByteUtilities\StarThrower.ByteUtilities.csproj" />
    <ProjectReference Include="..\StarThrower.Logging\StarThrower.Logging.csproj" />
    <ProjectReference Include="..\StarThrower.StringUtilities\StarThrower.StringUtilities.csproj" />
  </ItemGroup>

</Project>
