<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.4.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.4.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StarThrower.Gis.GeoUtilities\StarThrower.Gis.GeoUtilities.csproj" />
    <ProjectReference Include="..\StarThrower.MathUtilities\StarThrower.MathUtilities.csproj" />
    <ProjectReference Include="..\StarThrower.StringUtilities\StarThrower.StringUtilities.csproj" />
  </ItemGroup>

</Project>
